### ISSUE TITLE
Performance regression since v5.12.0

### ISSUE THREAD

**Issue by maplesteve** [SpiritIT/timezonecomplete#53] opened 2021-02-18 19:58 UTC
We see a huge performance difference between version v5.11.5 and v5.12.0.
I ran a test to measure the impact:
Version  | avg
--------|---
v5.12.1 |  3.718ms
v5.12.0 | 3.712ms
v5.11.5 |  581ms

This is factor 6!

The (passing) runs on Travis also show the difference - although I don't know if these times are representative:
[v5.11.5](https://travis-ci.org/github/SpiritIT/timezonecomplete/builds/758122442): 1:03m / 1:07m
[v5.12.1](https://travis-ci.org/github/SpiritIT/timezonecomplete/builds/758861675): 2:06m / 1:42m

**Comment by rogierschouten** [comment] 2021-02-18 20:47
Hi @maplesteve   yes that is the case.   The reason is that I first needed to get rid of a big bug, so I went for correctness over speed. The way the IANA TZ database is structured makes it very hard to calculate any DST transition without starting in like 1800 and going through the transitions linearly.   The reason there was a bug (#50) is that I tried to optimize it and failed quite miserably. 

You will notice the largest difference on dates far in the future. 

I should restructure the entire TzDatabase class but that would mean a breaking change. This class was written when TypeScript did not have the 'private' modifier yet and therefore all its methods are still public. That makes it hard to restructure as well. 

I do not have a lot of time in the upcoming weeks.  Is there a specific use case that is hurting you right now, so that I might try and optimize that?  Any code example that you need to run faster?

**Comment by rogierschouten** [comment] 2021-03-01 08:34
The piece of code you mention does not have nearly such a dramatic increase as the one mentioned in the first post. 
If I call that function 10000 times, I get 0.15 seconds for v5.12 and 0.14 seconds for v5.11

I think I am testing the wrong thing.  Is it possible to send me something closer to your use case?

**Comment by rogierschouten** [comment] 2021-03-18 20:11
@mplesteve I have not forgotten you but I simply didnt have the time yet. Can you still provide the code?

**Comment by maplesteve** [comment] 2021-03-18 22:32
> The piece of code you mention does not have nearly such a dramatic increase as the one mentioned in the first post.
> If I call that function 10000 times, I get 0.15 seconds for v5.12 and 0.14 seconds for v5.11
> 
> I think I am testing the wrong thing. Is it possible to send me something closer to your use case?

That's weird. Did you make the calls with a different date for each invocation?

I isolated the code related to timezonecomplete into separate functions and measured the calls (`aDate` is different for every call):

- For `beginningOfTomorrow` it's 121ms (v5.11.5) vs. 1102ms (v5.12.1) for 776 calls in total.
- For `calcNewDate` it's: 0.26 vs 1.41 (one call); it does `new tc.DateTime(aDate).toZone(tc.zone('Europe/Berlin'))`

- `new tc.DateTime(aDate).toZone(tc.zone('Europe/Berlin'))` is 0.13ms vs. 1.23ms (one call)

- Another function which basically does 776 times `new tc.DateTime(aDate).toZone(tc.zone(contractTimeZone)).toIsoString()` is 76.48ms vs. 827.36ms.

**Comment by rogierschouten** [comment] 2021-04-16 14:50
ok I did reproduce the regression now. Working on it

**Comment by rogierschouten** [comment] 2021-04-16 16:30
it' s much faster now. Released as 5.12.3. Can you try it?  It is not as fast as the old situation, but that is expected. But is it good enough for your use case now?

I will close this issue, please feel free to re-open if necessary.

**Closed by rogierschouten** 2021-04-16 16:30 UTC

**Comment by maplesteve** [comment] 2021-04-18 22:01
@rogierschouten I ran the tests against 5.12.3 and can confirm that it nearly has the performance of the 5.11.x versions. Thanks a lot for solving this!

**Comment by rogierschouten** [comment] 2021-04-19 16:53
@maplesteve Thank you for reporting & working with me!
